# Generated by Django 5.0.7 on 2024-07-26 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_cat_name_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='pro_mac',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.marca'),
        ),
    ]
