# Generated by Django 5.0.7 on 2024-07-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_marca_product_pro_mac'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='mac_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/marcas', verbose_name='Imagem da marca'),
        ),
    ]
