# Generated by Django 5.0.7 on 2024-07-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_marca_mac_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ano',
            field=models.IntegerField(default=2019, verbose_name='Ano do carro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço'),
        ),
    ]
