# Generated by Django 5.0.7 on 2024-07-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_ano_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('game', models.CharField(max_length=100)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prazo', models.DateField()),
                ('desc_cat', models.CharField(max_length=50)),
                ('des_image', models.ImageField(upload_to='descontos/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('not_desc', models.TextField()),
                ('not_image', models.ImageField(upload_to='noticias/')),
                ('data', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rev_desc', models.TextField()),
                ('rev_image', models.ImageField(upload_to='reviews/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pro_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pro_mac',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
