# Generated by Django 3.2.25 on 2024-08-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_desconto_noticia_review_delete_blog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='formulas/')),
            ],
        ),
        migrations.CreateModel(
            name='TipoCorreia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='tipos_correia/')),
            ],
        ),
        migrations.DeleteModel(
            name='Desconto',
        ),
        migrations.DeleteModel(
            name='Noticia',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
